# Generated by Django 3.2 on 2021-05-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meeting',
            table='meeting',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
